site_name: AsgeologeekFan çš„è‡ªç„¶è§‚å¯Ÿç¬”è®°
site_author: Haotian Fan
site_url: "https://asgeologeekfan.top/notebook"

theme:
  name: material
  language: zh
  font: false
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  custom_dir: overrides

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true

copyright: Copyright &copy; 2023 <a href="https://www.asgeologeekfan.top" target="_blank" rel="noopener">AsgeologeekFan</a>

nav:
  - "ğŸª¨åœ°è´¨":
      - rock/index.md
      - "å²©æµ†å²©": rock/igneous.md
      - "æ²‰ç§¯å²©": rock/sedimentary.md
      - "å˜è´¨å²©": rock/metamorphic.md
  - "âœ¨å¤©æ–‡":
      - star/index.md
      - "æ—¥é£Ÿ": star/sun.md
      - "æœˆé£Ÿ": star/moon.md
      - "æ˜Ÿåº§": star/constellation.md
      - "è¡Œæ˜Ÿ": star/planet.md
      - "å«æ˜Ÿ": star/satellite.md
  - "ğŸŒ¥ï¸äº‘ä¸å¤§æ°”å…‰å­¦":
      - atmosphere/index.md
      - "äº‘": atmosphere/cloud.md
      - "å…‰å­¦": atmosphere/halo.md
  - "ğŸ¦é¸Ÿç±»":
      - bird/index.md
      - "é›å½¢ç›®": bird/anseriformes.md
      - "é¸¡å½¢ç›®": bird/galliformes.md
      - "æ½œé¸Ÿç›®": bird/gaviiformes.md
      - "é¹±(hÃ¹)å½¢ç›®": bird/procellariiformes.md
      - "î¡¢î¡¡(pÃ¬ tÄ«)ç›®": bird/podicipediformes.md
      - "çº¢é¹³ç›®": bird/phoenicopteriformes.md
      - "é¹³å½¢ç›®": bird/ciconiiformes.md
      - "é¹ˆå½¢ç›®": bird/pelecaniformes.md
      - "é²£é¸Ÿç›®": bird/suliformes.md
      - "é¹°å½¢ç›®": bird/accipitriformes.md
      - "é¸¨å½¢ç›®": bird/otidiformes.md
      - "é¹¤å½¢ç›®": bird/gruiformes.md
      - "é¸»å½¢ç›®": bird/charadriiformes.md
      - "é¸½å½¢ç›®": bird/columbiformes.md
      - "é¹ƒå½¢ç›®": bird/cuculiformes.md
      - "é¸®å½¢ç›®": bird/strigiformes.md
      - "å¤œé¹°ç›®": bird/caprimulgiformes.md
      - "é›¨ç‡•ç›®": bird/apodiformes.md
      - "ä½›æ³•åƒ§ç›®": bird/coraciiformes.md
      - "çŠ€é¸Ÿç›®": bird/bucerotiformes.md
      - "î¡(lÃ¬e)å½¢ç›®": bird/piciformes.md
      - "éš¼å½¢ç›®": bird/falconiformes.md
      - "é›€å½¢ç›®": bird/passeriformes.md
  - "ğŸŒ¿èŠ±èŠ±è‰è‰":
      - plant/index.md


extra:
  analytics:
    provider: google
    property: G-1D6KT33V1L
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AsgeologeekFan
      name: Github
    - icon: fontawesome/solid/rss
      link: https://asgeologeekfan.top/
      name: Blog
    - icon: fontawesome/solid/house
      link: https://asgeologeekfan.top/notebook/
      name: Home

markdown_extensions:
  - attr_list
  - md_in_html
